---
title: "Lab report"
author: "Amir Rakhimov"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
  pdf_document: default
subtitle: National Institute of Genetics, Biological networks lab
---

# Goals
1. Compare different parameters of 2022-11-14  
2. Obtain taxonomic composition, make proper plots

# Methodology
## Software 
1. Ubuntu 20.04 LTS (Windows subsystem for Linux)
2. conda v22.9.0
3. Qiime2 v2022.8-py38-linux-conda

## Experimental workflow 1: use DADA2 (no truncation or trimming), pick OTUs, remove chimeras, retain borderline chimeras, classify
### 1.1 Import pandaseq demultiplexed single-end reads as **SingleEndFastqManifestPhred33V2**

```{bash, eval=FALSE}
qiime tools import \
  --type  'SampleData[SequencesWithQuality]' \
  --input-path filenames.txt \
  --output-path single-end-demux.qza \
  --input-format SingleEndFastqManifestPhred33V2 
  
# quality scores: 1 722 650 reads in total
qiime demux summarize \
  --i-data single-end-demux.qza \
  --o-visualization single-end-demux.qzv
# Min: 48678; Max: 49499; Mean: 49218.571429
```

### 1.2 Denoise with DADA2 (no truncation or trimming)
  
```{bash, eval=FALSE}
qiime dada2 denoise-single \
  --i-demultiplexed-seqs single-end-demux.qza \
  --p-trim-left 0 \
  --p-trunc-len 0 \
  --o-representative-sequences rep-seqs-dada2-no-trunc.qza \
  --o-table table-dada2-no-trunc.qza \
  --o-denoising-stats stats-dada2-no-trunc.qza \
  --p-n-threads 8 
  
######
# visualize your dada2 stats
qiime metadata tabulate \
  --m-input-file stats-dada2-no-trunc.qza \
  --o-visualization stats-dada2-no-trunc.qzv

# generate feature table (frequencies)
qiime feature-table summarize \
  --i-table table-dada2-no-trunc.qza \
  --o-visualization table-dada2-no-trunc.qzv

# generate feature table (sequences)
qiime feature-table tabulate-seqs \
  --i-data rep-seqs-dada2-no-trunc.qza \
  --o-visualization rep-seqs-dada2-no-trunc.qzv 
```

### 1.3 Cluster into 97% identical OTUs
```{bash, eval=FALSE}
qiime vsearch cluster-features-de-novo \
  --i-table table-dada2-no-trunc.qza \
  --i-sequences rep-seqs-dada2-no-trunc.qza \
  --p-perc-identity 0.97 \
  --o-clustered-table table-dada2-no-trunc-dn-97.qza \
  --o-clustered-sequences rep-seqs-dada2-no-trunc-dn-97.qza

## visualize clustering results
qiime feature-table tabulate-seqs \
  --i-data rep-seqs-dada2-no-trunc-dn-97.qza \
  --o-visualization rep-seqs-dada2-no-trunc-dn-97.qzv 
```

### 1.4 Chimera check and filter
  + de novo check with uchime


```{bash, eval = FALSE}
# chimera check: de novo with uchime
qiime vsearch uchime-denovo \
  --i-table table-dada2-no-trunc-dn-97.qza \
  --i-sequences rep-seqs-dada2-no-trunc-dn-97.qza \
  --output-dir uchime-dada2-no-trunc-dn-out-97
  
## visualize summary stats
qiime metadata tabulate \
  --m-input-file uchime-dada2-no-trunc-dn-out-97/stats.qza \
  --o-visualization uchime-dada2-no-trunc-dn-out-97/stats.qzv
```


  + exclude chimeras but retain borderline chimeras
```{bash, eval = FALSE}
# chimera filtering: retain borderline
qiime feature-table filter-features \
  --i-table table-dada2-no-trunc-dn-97.qza \
  --m-metadata-file uchime-dada2-no-trunc-dn-out-97/chimeras.qza \
  --p-exclude-ids \
  --o-filtered-table uchime-dada2-no-trunc-dn-out-97/table-dada2-no-trunc-dn-97-uchime-nonchimeric-w-borderline.qza
  
qiime feature-table filter-seqs \
  --i-data rep-seqs-dada2-no-trunc-dn-97.qza \
  --m-metadata-file uchime-dada2-no-trunc-dn-out-97/chimeras.qza \
  --p-exclude-ids \
  --o-filtered-data uchime-dada2-no-trunc-dn-out-97/rep-seqs-dada2-no-trunc-dn-97-uchime-nonchimeric-w-borderline.qza
  
qiime feature-table summarize \
  --i-table uchime-dada2-no-trunc-dn-out-97/table-dada2-no-trunc-dn-97-uchime-nonchimeric-w-borderline.qza \
  --o-visualization uchime-dada2-no-trunc-dn-out-97/table-dada2-no-trunc-dn-97-uchime-nonchimeric-w-borderline.qzv
```

### 1.5 Taxonomic classification
  + Use Greengenes 13_5 database with 97% identical OTUs
  + Import FASTA sequences of OTUs as a QIIME artifact
```{bash, eval = FALSE}
# import otus
qiime tools import \
  --type 'FeatureData[Sequence]' \
  --input-path ./gg_13_5_otus/rep_set/97_otus.fasta \
  --output-path gg_13_5_97_otus.qza
```

  + Import taxonomical information as HeaderlessTSVTaxonomyFormat

```{bash, eval = FALSE}
# import taxonomy
qiime tools import \
  --type 'FeatureData[Taxonomy]' \
  --input-format HeaderlessTSVTaxonomyFormat \
  --input-path ./gg_13_5_otus/taxonomy/97_otu_taxonomy.txt \
  --output-path gg_13_5_97_ref-taxonomy.qza
```
  
  + Extract reference reads for classification : no truncation, no minimal/maximal length filtering
```{bash, eval = FALSE}
# extract reference reads: no truncation, no min or max length filtering
qiime feature-classifier extract-reads \
  --i-sequences gg_13_5_97_otus.qza \
  --p-f-primer CCTACGGGNGGCWGCAG \
  --p-r-primer GACTACHVGGGTATCTAATCC \
  --p-trunc-len -1 \
  --p-min-length 0 \
  --p-max-length 0 \
  --o-reads gg_13_5_97_ref-seqs-no-minmax-no-len-filter.qza
```  

Primers: S-D-Bact-0341-b-S-17 (5'-CCTACGGGNGGCWGCAG-3') and S-D-Bact-0785-a-A-21 (5'-GACTACHVGGGTATCTAATCC-3') 

  + Train the Naive Bayes classifier
```{bash, eval = FALSE}
# train the classifier
qiime feature-classifier fit-classifier-naive-bayes \
  --i-reference-reads gg_13_5_97_ref-seqs-no-minmax-no-len-filter.qza \
  --i-reference-taxonomy gg_13_5_97_ref-taxonomy.qza \
  --o-classifier gg_13_5_97_classifier-no-minmax-no-len-filter.qza
```  

  + Test the classifier
```{bash}
# test the classifier
qiime feature-classifier classify-sklearn \
  --i-classifier gg_13_5_97_classifier-no-minmax-no-len-filter.qza \
  --i-reads uchime-dada2-no-trunc-dn-out-97/rep-seqs-dada2-no-trunc-dn-97-uchime-nonchimeric-w-borderline.qza \
  --o-classification taxonomy-dada2-no-trunc-dn-97-uchime-nonchimeric-w-borderline-no-minmax-no-len-filter.qza

qiime metadata tabulate \
  --m-input-file taxonomy-dada2-no-trunc-dn-97-uchime-nonchimeric-w-borderline-no-minmax-no-len-filter.qza \
  --o-visualization taxonomy-dada2-no-trunc-dn-97-uchime-nonchimeric-w-borderline-no-minmax-no-len-filter.qzv
```


  + Generate taxa bar plots
```{bash, eval = FALSE}
# taxa bar plots
qiime taxa barplot \
  --i-table uchime-dada2-no-trunc-dn-out-97/table-dada2-no-trunc-dn-97-uchime-nonchimeric-w-borderline.qza \
  --i-taxonomy taxonomy-dada2-no-trunc-dn-97-uchime-nonchimeric-w-borderline-no-minmax-no-len-filter.qza \
  --m-metadata-file filenames.txt \
  --o-visualization taxa-bar-plots-dada2-no-trunc-dn-97-uchime-w-borderline-no-minmax-no-len-filter.qzv
```


## Experimental workflow 2: use DADA2, pick OTUs, remove chimeras and borderline chimeras, classify
### 2.1 Import pandaseq demultiplexed single-end reads as **SingleEndFastqManifestPhred33V2**

```{bash, eval=FALSE}
qiime tools import \
  --type  'SampleData[SequencesWithQuality]' \
  --input-path filenames.txt \
  --output-path single-end-demux.qza \
  --input-format SingleEndFastqManifestPhred33V2 
  
# quality scores: 1 722 650 reads in total
qiime demux summarize \
  --i-data single-end-demux.qza \
  --o-visualization single-end-demux.qzv
# Min: 48678; Max: 49499; Mean: 49218.571429
```

### 2.2 Denoise with DADA2 (no truncation or trimming)
  
```{bash, eval=FALSE}
qiime dada2 denoise-single \
  --i-demultiplexed-seqs single-end-demux.qza \
  --p-trim-left 0 \
  --p-trunc-len 0 \
  --o-representative-sequences rep-seqs-dada2-no-trunc.qza \
  --o-table table-dada2-no-trunc.qza \
  --o-denoising-stats stats-dada2-no-trunc.qza \
  --p-n-threads 8 
  
######
# visualize your dada2 stats
qiime metadata tabulate \
  --m-input-file stats-dada2-no-trunc.qza \
  --o-visualization stats-dada2-no-trunc.qzv

# generate feature table (frequencies)
qiime feature-table summarize \
  --i-table table-dada2-no-trunc.qza \
  --o-visualization table-dada2-no-trunc.qzv

# generate feature table (sequences)
qiime feature-table tabulate-seqs \
  --i-data rep-seqs-dada2-no-trunc.qza \
  --o-visualization rep-seqs-dada2-no-trunc.qzv 
```

### 2.3 Cluster into 97% identical OTUs
```{bash, eval=FALSE}
qiime vsearch cluster-features-de-novo \
  --i-table table-dada2-no-trunc.qza \
  --i-sequences rep-seqs-dada2-no-trunc.qza \
  --p-perc-identity 0.97 \
  --o-clustered-table table-dada2-no-trunc-dn-97.qza \
  --o-clustered-sequences rep-seqs-dada2-no-trunc-dn-97.qza

## visualize clustering results
qiime feature-table tabulate-seqs \
  --i-data rep-seqs-dada2-no-trunc-dn-97.qza \
  --o-visualization rep-seqs-dada2-no-trunc-dn-97.qzv 
```

### 2.4 Chimera check and filter
  + de novo check with uchime


```{bash, eval = FALSE}
# chimera check: de novo with uchime
qiime vsearch uchime-denovo \
  --i-table table-dada2-no-trunc-dn-97.qza \
  --i-sequences rep-seqs-dada2-no-trunc-dn-97.qza \
  --output-dir uchime-dada2-no-trunc-dn-out-97
  
## visualize summary stats
qiime metadata tabulate \
  --m-input-file uchime-dada2-no-trunc-dn-out-97/stats.qza \
  --o-visualization uchime-dada2-no-trunc-dn-out-97/stats.qzv
```

  + remove chimeras and borderline chimeras
```{bash}
# chimera filtering 2: remove borderline
qiime feature-table filter-features \
  --i-table table-dada2-no-trunc-dn-97.qza \
  --m-metadata-file uchime-dada2-no-trunc-dn-out-97/chimeras.qza \
  --o-filtered-table uchime-dada2-no-trunc-dn-out-97/table-dada2-no-trunc-dn-97-uchime-nonchimeric-no-borderline.qza
  
qiime feature-table filter-seqs \
  --i-data rep-seqs-dada2-no-trunc-dn-97.qza \
  --m-metadata-file uchime-dada2-no-trunc-dn-out-97/chimeras.qza \
  --o-filtered-data uchime-dada2-no-trunc-dn-out-97/rep-seqs-dada2-no-trunc-dn-97-nonchimeric-no-borderline.qza
  
qiime feature-table summarize \
  --i-table uchime-dada2-no-trunc-dn-out-97/table-dada2-no-trunc-dn-97-uchime-nonchimeric-no-borderline.qza \
  --o-visualization uchime-dada2-no-trunc-dn-out-97/table-dada2-no-trunc-dn-97-uchime-nonchimeric-no-borderline.qzv
```

### 2.5 Taxonomic classification
  + Use Greengenes 13_5 database with 97% identical OTUs
  + Import FASTA sequences of OTUs as a QIIME artifact
```{bash, eval = FALSE}
# import otus
qiime tools import \
  --type 'FeatureData[Sequence]' \
  --input-path ./gg_13_5_otus/rep_set/97_otus.fasta \
  --output-path gg_13_5_97_otus.qza
```

  + Import taxonomical information as HeaderlessTSVTaxonomyFormat

```{bash, eval = FALSE}
# import taxonomy
qiime tools import \
  --type 'FeatureData[Taxonomy]' \
  --input-format HeaderlessTSVTaxonomyFormat \
  --input-path ./gg_13_5_otus/taxonomy/97_otu_taxonomy.txt \
  --output-path gg_13_5_97_ref-taxonomy.qza
```
  
  + Extract reference reads for classification : no truncation, no minimal/maximal length filtering
```{bash, eval = FALSE}
# extract reference reads: no truncation, no min or max length filtering
qiime feature-classifier extract-reads \
  --i-sequences gg_13_5_97_otus.qza \
  --p-f-primer CCTACGGGNGGCWGCAG \
  --p-r-primer GACTACHVGGGTATCTAATCC \
  --p-trunc-len -1 \
  --p-min-length 0 \
  --p-max-length 0 \
  --o-reads gg_13_5_97_ref-seqs-no-minmax-no-len-filter.qza
```  

Primers: S-D-Bact-0341-b-S-17 (5'-CCTACGGGNGGCWGCAG-3') and S-D-Bact-0785-a-A-21 (5'-GACTACHVGGGTATCTAATCC-3') 

  + Train the Naive Bayes classifier
```{bash}
# train the classifier
qiime feature-classifier fit-classifier-naive-bayes \
  --i-reference-reads gg_13_5_97_ref-seqs-no-minmax-no-len-filter.qza \
  --i-reference-taxonomy gg_13_5_97_ref-taxonomy.qza \
  --o-classifier gg_13_5_97_classifier-no-minmax-no-len-filter.qza
```

  + Test the classifier
```{bash}
# test the classifier
qiime feature-classifier classify-sklearn \
  --i-classifier gg_13_5_97_classifier-no-minmax-no-len-filter.qza \
  --i-reads uchime-dada2-no-trunc-dn-out-97/rep-seqs-dada2-no-trunc-dn-97-uchime-nonchimeric-no-borderline.qza \
  --o-classification taxonomy-dada2-no-trunc-dn-97-uchime-nonchimeric-no-borderline-no-minmax-no-len-filter.qza

qiime metadata tabulate \
  --m-input-file taxonomy-dada2-no-trunc-dn-97-uchime-nonchimeric-no-borderline-no-minmax-no-len-filter.qza \
  --o-visualization taxonomy-dada2-no-trunc-dn-97-uchime-nonchimeric-no-borderline-no-minmax-no-len-filter.qzv
```

  + Generate taxa bar plots
```{bash}
# taxa bar plots
qiime taxa barplot \
  --i-table uchime-dada2-no-trunc-dn-out-97/table-dada2-no-trunc-dn-97-uchime-nonchimeric-no-borderline.qza \
  --i-taxonomy taxonomy-dada2-no-trunc-dn-97-uchime-nonchimeric-no-borderline-no-minmax-no-len-filter.qza \
  --m-metadata-file filenames.txt \
  --o-visualization taxa-bar-plots-dada2-no-trunc-dn-97-uchime-no-borderline-no-minmax-no-len-filter.qzv
```


## Experimental workflow 3: run dada2 without truncation or trimming, classify
### 3.1 Import pandaseq demultiplexed single-end reads as **SingleEndFastqManifestPhred33V2**

```{bash, eval=FALSE}
qiime tools import \
  --type  'SampleData[SequencesWithQuality]' \
  --input-path filenames.txt \
  --output-path single-end-demux.qza \
  --input-format SingleEndFastqManifestPhred33V2 
  
# quality scores: 1 722 650 reads in total
qiime demux summarize \
  --i-data single-end-demux.qza \
  --o-visualization single-end-demux.qzv
# Min: 48678; Max: 49499; Mean: 49218.571429
```

### 3.2 Denoise with DADA2 (no truncation or trimming)
  
```{bash, eval=FALSE}
qiime dada2 denoise-single \
  --i-demultiplexed-seqs single-end-demux.qza \
  --p-trim-left 0 \
  --p-trunc-len 0 \
  --o-representative-sequences rep-seqs-dada2-no-trunc.qza \
  --o-table table-dada2-no-trunc.qza \
  --o-denoising-stats stats-dada2-no-trunc.qza \
  --p-n-threads 8 
  
######
# visualize your dada2 stats
qiime metadata tabulate \
  --m-input-file stats-dada2-no-trunc.qza \
  --o-visualization stats-dada2-no-trunc.qzv

# generate feature table (frequencies)
qiime feature-table summarize \
  --i-table table-dada2-no-trunc.qza \
  --o-visualization table-dada2-no-trunc.qzv

# generate feature table (sequences)
qiime feature-table tabulate-seqs \
  --i-data rep-seqs-dada2-no-trunc.qza \
  --o-visualization rep-seqs-dada2-no-trunc.qzv 
```

### 3.3 Taxonomic classification
  + Use Greengenes 13_5 database with 97% identical OTUs
  + Import FASTA sequences of OTUs as a QIIME artifact
```{bash, eval = FALSE}
# import otus
qiime tools import \
  --type 'FeatureData[Sequence]' \
  --input-path ./gg_13_5_otus/rep_set/97_otus.fasta \
  --output-path gg_13_5_97_otus.qza
```

  + Import taxonomical information as HeaderlessTSVTaxonomyFormat

```{bash, eval = FALSE}
# import taxonomy
qiime tools import \
  --type 'FeatureData[Taxonomy]' \
  --input-format HeaderlessTSVTaxonomyFormat \
  --input-path ./gg_13_5_otus/taxonomy/97_otu_taxonomy.txt \
  --output-path gg_13_5_97_ref-taxonomy.qza
```
  
  + Extract reference reads for classification : no truncation, no minimal/maximal length filtering
```{bash, eval = FALSE}
# extract reference reads: no truncation, no min or max length filtering
qiime feature-classifier extract-reads \
  --i-sequences gg_13_5_97_otus.qza \
  --p-f-primer CCTACGGGNGGCWGCAG \
  --p-r-primer GACTACHVGGGTATCTAATCC \
  --p-trunc-len -1 \
  --p-min-length 0 \
  --p-max-length 0 \
  --o-reads gg_13_5_97_ref-seqs-no-minmax-no-len-filter.qza
```  

Primers: S-D-Bact-0341-b-S-17 (5'-CCTACGGGNGGCWGCAG-3') and S-D-Bact-0785-a-A-21 (5'-GACTACHVGGGTATCTAATCC-3') 

  + Train the Naive Bayes classifier
```{bash}
# train the classifier
qiime feature-classifier fit-classifier-naive-bayes \
  --i-reference-reads gg_13_5_97_ref-seqs-no-minmax-no-len-filter.qza \
  --i-reference-taxonomy gg_13_5_97_ref-taxonomy.qza \
  --o-classifier gg_13_5_97_classifier-no-minmax-no-len-filter.qza
```

  + Test the classifier
```{bash}
# test the classifier
qiime feature-classifier classify-sklearn \
  --i-classifier gg_13_5_97_classifier-no-minmax-no-len-filter.qza \
  --i-reads rep-seqs-dada2-no-trunc.qza \
  --o-classification taxonomy-dada2-no-trunc.qza

qiime metadata tabulate \
  --m-input-file taxonomy-dada2-no-trunc.qza \
  --o-visualization taxonomy-dada2-no-trunc.qzv
```

  + Generate taxa bar plots
```{bash}
# taxa bar plots
qiime taxa barplot \
  --i-table table-dada2-no-trunc.qza \
  --i-taxonomy taxonomy-dada2-no-trunc.qza \
  --m-metadata-file filenames.txt \
  --o-visualization taxa-bar-plots-dada2-no-trunc.qzv
```


# Results:
In raw reads, 1 722 650 reads in total
Min: 48678; Max: 49499; Mean: 49218.571429

